[logger]
# Уровень логирования (info - логгировать все, error - только ошибки)
level = "info"

# memory или sql
[storage]
storage = "memory"

[sql]
dsn = "postgres://calendar:calendar@localhost/calendar"